name: whatsappcloneflutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_svg: 0.17.4
  fluttertoast: 4.0.0
  url_launcher: 5.4.7
  country_code_picker: 1.3.12+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - icons/
