name: whatsappcloneflutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_svg: 0.17.4
  fluttertoast: 4.0.1
  url_launcher: 5.4.10
  dio: 3.0.9
  flutter_bloc: 4.0.0
  equatable: 1.1.1
  flutter_statusbarcolor: 0.2.3
  mobile_number: 1.0.2
  phone_number: 0.6.2+3
  device_info: 0.4.2+4
  firebase_messaging: 6.0.16
  shared_preferences: 0.5.7+3
  material_design_icons_flutter: 4.0.5345
  permission_handler: 5.0.1
  contacts_service: 0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - icons/
